"""
htm/htm_generate_configs.py
Generate random HTM hyperparameter configurations and the SLURM submission script.

Usage:
  python htm/htm_generate_configs.py [--n-configs 64] [--seed 0]

Outputs (relative to project root):
  configs/config_0000.json … configs/config_NNNN.json
  slurm/submit_array.sh
"""

import argparse
import json
import os
import random
from pathlib import Path

# ------------------------------------------------------------------
# Search space
# ------------------------------------------------------------------
PARAM_SPACE = {
    # SpatialPooler
    # Round 3 (128 runs): sp_act=20 in ranks 1,2,4; 40 rank 3; 60/80 rank 5+
    # removed 80 (never top-4); added 15,30 as intermediates in winning 20-40 range
    # pct=0.7 in 3/5 top configs; 0.5 in 2/5; added 0.75 to probe above 0.7
    # boost=0 confirmed fixed across all 128 runs
    "sp_columnDimensions":   [2048],
    "sp_numActiveColumns":   [10, 15, 20, 30, 40],  # removed 60,80 (ranks 5+); added 15,30 as intermediates
    "sp_potentialPct":       [0.5, 0.6, 0.7, 0.75], # added 0.75 (0.7 dominant in top-5: 3/5)
    "sp_boostStrength":      [0.0],                # fixed: boost>0 killed all tested configs
    "sp_synPermActiveInc":   [0.02, 0.05, 0.10],
    "sp_synPermConnected":   [0.10, 0.20],
    "sp_synPermInactiveDec": [0.003, 0.005, 0.010],
    # TemporalMemory
    # Round 3: tm=16 in top-5 (3/5); 32 viable (2/5); 8 untested exploratory
    # act=15 best (3/5 top), act=20 rank 1, act=13 rank 5; added 18 as intermediate
    # min=11 dominant (3/5 top, 10/20 overall)
    "tm_cellsPerColumn":      [8, 16, 32],            # 16 dominant (3/5 top); 8 untested
    "tm_activationThreshold": [13, 14, 15, 18, 20],  # added 18 between 15 (ranks 2-4) and 20 (rank 1)
    "tm_minThreshold":        [10, 11, 12],           # 11 dominant (3/5 top)
    "tm_maxNewSynapseCount":  [15, 20, 30],
    "tm_initialPermanence":   [0.21, 0.31, 0.40],
    "tm_connectedPermanence": [0.30, 0.50],
    "tm_permanenceIncrement": [0.05, 0.10, 0.20],
    "tm_permanenceDecrement": [0.03, 0.05, 0.10],
    # Encoder
    # Round 3: enc=16 dominates (18/20 top); w=7 best in top-5 (3/5), w=5 rank 1; w=4 untested
    "enc_bits_per_feature": [16, 32],
    "enc_w":                [4, 5, 6, 7],
    # Detection strategy — AL never helped; fixed to False
    "use_anomaly_likelihood": [False],
    # Warmup: initial windows skipped before any alarm can fire (first_crossing sensitive to this)
    "warmup_steps": [3, 5, 8, 12, 20],
}

# config_0000 is always the "default" from htm_train_interactive.py
DEFAULT_CONFIG = {
    # Best known config (cfg0075: val F1=0.375, test F1=0.7429)
    "sp_columnDimensions":   2048,
    "sp_numActiveColumns":   20,
    "sp_potentialPct":       0.5,
    "sp_boostStrength":      0.0,
    "sp_synPermActiveInc":   0.05,
    "sp_synPermConnected":   0.10,
    "sp_synPermInactiveDec": 0.005,
    "tm_cellsPerColumn":     16,
    "tm_activationThreshold":20,
    "tm_minThreshold":       11,
    "tm_maxNewSynapseCount": 20,
    "tm_initialPermanence":  0.21,
    "tm_connectedPermanence":0.50,
    "tm_permanenceIncrement":0.10,
    "tm_permanenceDecrement":0.10,
    "enc_bits_per_feature":  16,
    "enc_w":                 5,
    # Detection strategy (al_learning_period is fixed, not searched)
    "detection_mode":         "first_crossing",
    "use_anomaly_likelihood": False,
    "al_learning_period":     20,
    "warmup_steps":           5,
    "seed":                   42,
}


# ------------------------------------------------------------------
# Constraint checker
# ------------------------------------------------------------------
def is_valid(cfg):
    """HTM requires certain ordering constraints between parameters."""
    if cfg["enc_w"] >= cfg["enc_bits_per_feature"]:
        return False
    if cfg["tm_minThreshold"] > cfg["tm_activationThreshold"]:
        return False
    if cfg["tm_activationThreshold"] > cfg["tm_maxNewSynapseCount"]:
        return False
    return True


def sample_config(rng):
    for _ in range(1000):
        cfg = {k: rng.choice(v) for k, v in PARAM_SPACE.items()}
        if is_valid(cfg):
            return cfg
    return None


# ------------------------------------------------------------------
# SLURM script
# ------------------------------------------------------------------
def write_slurm_script(n_configs, out_path):
    script = f"""\
#!/bin/bash
# ============================================================
# SLURM job array for HTM hyperparameter search
# Generated by htm/htm_generate_configs.py
#
# Submit with:
#   sbatch slurm/submit_array.sh
# ============================================================
#SBATCH --job-name=htm_search
#SBATCH --output=logs/slurm_%A_%a.out
#SBATCH --error=logs/slurm_%A_%a.err
#SBATCH --array=0-{n_configs - 1}%200  # max 200 concurrent tasks (stays under 300-CPU QOS limit)
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=01:30:00
# Adjust partition / account to match your Newton allocation:
##SBATCH --partition=<partition>
##SBATCH --account=<account>

# ---- Environment ------------------------------------------------
# Uncomment and edit ONE of the following to activate your env:
# module load python/3.10
# source /path/to/.venv/bin/activate

# ---- Run this task's config ------------------------------------
# Array index → config file (zero-padded, sorted alphabetically)
mapfile -t CONFIGS < <(ls configs/config_*.json | sort)
CONFIG="${{CONFIGS[$SLURM_ARRAY_TASK_ID]}}"

if [[ -z "$CONFIG" ]]; then
    echo "ERROR: No config for task $SLURM_ARRAY_TASK_ID"
    exit 1
fi

echo "========================================"
echo "Task  : $SLURM_ARRAY_TASK_ID"
echo "Config: $CONFIG"
echo "Node  : $(hostname)"
echo "========================================"

python htm/htm_train_single.py --config "$CONFIG"
"""
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, 'w', newline='\n') as fh:   # Unix line-endings for bash
        fh.write(script)
    print(f"SLURM script  → {out_path}")


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------
def main():
    # Run from project root so configs/ and slurm/ are at root level
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(project_root)

    parser = argparse.ArgumentParser(
        description="Generate HTM hyperparameter configs and SLURM script")
    parser.add_argument("--n-configs", type=int, default=64,
                        help="Total configs to generate (default: 64)")
    parser.add_argument("--seed", type=int, default=0,
                        help="RNG seed for config sampling (default: 0)")
    args = parser.parse_args()

    os.makedirs("configs", exist_ok=True)
    os.makedirs("logs",    exist_ok=True)

    rng     = random.Random(args.seed)
    configs = [DEFAULT_CONFIG.copy()]   # index 0 = current default
    seen    = {json.dumps(DEFAULT_CONFIG, sort_keys=True)}

    while len(configs) < args.n_configs:
        cfg = sample_config(rng)
        if cfg is None:
            print("WARNING: Could not sample more valid configs.")
            break
        cfg["seed"] = rng.randint(0, 99999)
        key = json.dumps(cfg, sort_keys=True)
        if key not in seen:
            seen.add(key)
            configs.append(cfg)

    for idx, cfg in enumerate(configs):
        path = f"configs/config_{idx:04d}.json"
        with open(path, 'w') as fh:
            json.dump(cfg, fh, indent=2)

    print(f"Generated {len(configs)} configs → configs/")
    write_slurm_script(len(configs), "slurm/submit_array.sh")

    print(f"\nWorkflow:")
    print(f"  1. python htm/htm_prepare_data.py      # once, on login node")
    print(f"  2. sbatch slurm/submit_array.sh        # submit {len(configs)} jobs")
    print(f"  3. python htm/htm_collect_results.py   # after all jobs finish")


if __name__ == "__main__":
    main()
