#!/bin/bash
# ============================================================
# SLURM job array for HTM hyperparameter search
# Generated by htm/htm_generate_configs.py
#
# Submit with:
#   sbatch slurm/submit_array.sh
# ============================================================
#SBATCH --job-name=htm_search
#SBATCH --output=logs/slurm_%A_%a.out
#SBATCH --error=logs/slurm_%A_%a.err
#SBATCH --array=0-63%200  # max 200 concurrent tasks (stays under 300-CPU QOS limit)
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=01:30:00
# Adjust partition / account to match your Newton allocation:
##SBATCH --partition=<partition>
##SBATCH --account=<account>

# ---- Environment ------------------------------------------------
# Uncomment and edit ONE of the following to activate your env:
# module load python/3.10
# source /path/to/.venv/bin/activate

# ---- Run this task's config ------------------------------------
# Array index → config file (zero-padded, sorted alphabetically)
# Old configs are deleted before each generation run, so configs/ only
# contains the current batch; array task IDs map 1:1 to sorted files.
mapfile -t CONFIGS < <(ls configs/config_*.json | sort)
CONFIG="${CONFIGS[$SLURM_ARRAY_TASK_ID]}"

if [[ -z "$CONFIG" ]]; then
    echo "ERROR: No config for task $SLURM_ARRAY_TASK_ID"
    exit 1
fi

echo "========================================"
echo "Task  : $SLURM_ARRAY_TASK_ID"
echo "Config: $CONFIG"
echo "Node  : $(hostname)"
echo "========================================"

python htm/htm_train_single.py --config "$CONFIG"
