#!/bin/bash
# ============================================================
# SLURM job array for HTM-Combined hyperparameter search
# Generated by htm_combined/htm_combined_generate_configs.py
#
# Submit with:
#   sbatch slurm/hc_submit_array.sh
# ============================================================
#SBATCH --job-name=hc_htm
#SBATCH --output=logs/hc_%A_%a.out
#SBATCH --error=logs/hc_%A_%a.err
#SBATCH --array=0-4%200
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
#SBATCH --time=08:00:00
##SBATCH --partition=<partition>
##SBATCH --account=<account>

# ---- Environment ------------------------------------------------
source $(conda info --base)/etc/profile.d/conda.sh
conda activate htm_keyboard_1

# ---- Run this task's config ------------------------------------
mapfile -t CONFIGS < <(ls hc_configs/config_*.json | sort)
CONFIG="${CONFIGS[$SLURM_ARRAY_TASK_ID]}"

if [[ -z "$CONFIG" ]]; then
    echo "ERROR: No config for task $SLURM_ARRAY_TASK_ID"
    exit 1
fi

echo "========================================"
echo "Task  : $SLURM_ARRAY_TASK_ID"
echo "Config: $CONFIG"
echo "Node  : $(hostname)"
echo "========================================"

python htm_combined/htm_combined_train_single.py --config "$CONFIG"
