"""
mlp/mlp_generate_configs.py
Generate random MLP hyperparameter configurations and the SLURM submission script.

Usage:
  python mlp/mlp_generate_configs.py [--n-configs 128] [--seed 0]

Outputs (relative to project root):
  mlp_configs/config_0000.json … mlp_configs/config_NNNN.json
  slurm/mlp_submit_array.sh
"""

import argparse
import json
import os
import random
from pathlib import Path

# ------------------------------------------------------------------
# Search space
# ------------------------------------------------------------------
PARAM_SPACE = {
    "n_layers":        [2, 3, 4, 5],
    # hidden_dims: sampled n_layers times from this list (see sample_config)
    "hidden_dim_choices": [32, 64, 128, 256, 512],
    "dropout":         [0.0, 0.1, 0.2, 0.3, 0.4, 0.5],
    "batch_norm":      [True, False],
    "activation":      ["relu", "leaky_relu", "elu", "gelu"],
    "optimizer":       ["adam", "adamw"],
    "lr":              [1e-5, 3e-5, 1e-4, 3e-4, 1e-3, 3e-3, 1e-2],
    "weight_decay":    [1e-6, 1e-5, 1e-4, 1e-3, 1e-2],
    "scheduler":       ["cosine", "cosine_warm", "reduce_on_plateau", "one_cycle"],
    "batch_size":      [16, 32, 64, 128],
    "label_smoothing": [0.0, 0.05, 0.10, 0.15],
}

# config_0000 = sensible default
DEFAULT_CONFIG = {
    "hidden_dims":     [128, 64, 32],
    "dropout":         0.3,
    "batch_norm":      True,
    "activation":      "relu",
    "optimizer":       "adamw",
    "lr":              1e-3,
    "weight_decay":    1e-4,
    "scheduler":       "cosine",
    "batch_size":      64,
    "label_smoothing": 0.0,
    "seed":            42,
}


def sample_config(rng):
    n_layers   = rng.choice(PARAM_SPACE["n_layers"])
    hidden_dims = [rng.choice(PARAM_SPACE["hidden_dim_choices"]) for _ in range(n_layers)]
    return {
        "hidden_dims":     hidden_dims,
        "dropout":         rng.choice(PARAM_SPACE["dropout"]),
        "batch_norm":      rng.choice(PARAM_SPACE["batch_norm"]),
        "activation":      rng.choice(PARAM_SPACE["activation"]),
        "optimizer":       rng.choice(PARAM_SPACE["optimizer"]),
        "lr":              rng.choice(PARAM_SPACE["lr"]),
        "weight_decay":    rng.choice(PARAM_SPACE["weight_decay"]),
        "scheduler":       rng.choice(PARAM_SPACE["scheduler"]),
        "batch_size":      rng.choice(PARAM_SPACE["batch_size"]),
        "label_smoothing": rng.choice(PARAM_SPACE["label_smoothing"]),
        "seed":            rng.randint(0, 99999),
    }


# ------------------------------------------------------------------
# SLURM script
# ------------------------------------------------------------------
def write_slurm_script(n_configs, out_path):
    script = f"""\
#!/bin/bash
# ============================================================
# SLURM job array for MLP hyperparameter search
# Generated by mlp/mlp_generate_configs.py
#
# Submit with:
#   sbatch slurm/mlp_submit_array.sh
# ============================================================
#SBATCH --job-name=mlp_search
#SBATCH --output=logs/mlp_%A_%a.out
#SBATCH --error=logs/mlp_%A_%a.err
#SBATCH --array=0-{n_configs - 1}%200  # max 200 concurrent tasks
#SBATCH --cpus-per-task=2
#SBATCH --mem=4G
#SBATCH --time=00:20:00
# GPU not needed: 14-dim input, ~50K rows — CPU compute cost < 600 MB total.
# GPU transfer overhead exceeds compute savings for this dataset size.
##SBATCH --gres=gpu:1
# Adjust partition / account to match your Newton allocation:
##SBATCH --partition=<partition>
##SBATCH --account=<account>

# ---- Environment ------------------------------------------------
# Uncomment and edit ONE of the following to activate your env:
# module load python/3.10
# source /path/to/.venv/bin/activate

# ---- Run this task's config ------------------------------------
mapfile -t CONFIGS < <(ls mlp_configs/config_*.json | sort)
CONFIG="${{CONFIGS[$SLURM_ARRAY_TASK_ID]}}"

if [[ -z "$CONFIG" ]]; then
    echo "ERROR: No config for task $SLURM_ARRAY_TASK_ID"
    exit 1
fi

echo "========================================"
echo "Task  : $SLURM_ARRAY_TASK_ID"
echo "Config: $CONFIG"
echo "Node  : $(hostname)"
echo "========================================"

python mlp/mlp_train_single.py --config "$CONFIG"
"""
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, 'w', newline='\n') as fh:   # Unix line-endings for bash
        fh.write(script)
    print(f"SLURM script  → {out_path}")


# ------------------------------------------------------------------
# Main
# ------------------------------------------------------------------
def main():
    project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(project_root)

    parser = argparse.ArgumentParser(
        description="Generate MLP hyperparameter configs and SLURM script")
    parser.add_argument("--n-configs", type=int, default=128,
                        help="Total configs to generate (default: 128)")
    parser.add_argument("--seed", type=int, default=0,
                        help="RNG seed for config sampling (default: 0)")
    args = parser.parse_args()

    os.makedirs("mlp_configs", exist_ok=True)
    os.makedirs("logs",        exist_ok=True)

    rng     = random.Random(args.seed)
    configs = [DEFAULT_CONFIG.copy()]
    seen    = {json.dumps(DEFAULT_CONFIG, sort_keys=True)}

    while len(configs) < args.n_configs:
        cfg = sample_config(rng)
        key = json.dumps(cfg, sort_keys=True)
        if key not in seen:
            seen.add(key)
            configs.append(cfg)

    for idx, cfg in enumerate(configs):
        path = f"mlp_configs/config_{idx:04d}.json"
        with open(path, 'w') as fh:
            json.dump(cfg, fh, indent=2)

    print(f"Generated {len(configs)} configs → mlp_configs/")
    write_slurm_script(len(configs), "slurm/mlp_submit_array.sh")

    print(f"\nWorkflow:")
    print(f"  1. python mlp/mlp_prepare_data.py       # once, uses split.pkl for humans")
    print(f"  2. python mlp/mlp_balance_train.py      # once, balance train split")
    print(f"  3. python mlp/mlp_generate_configs.py --n-configs {args.n_configs}")
    print(f"  4. sbatch slurm/mlp_submit_array.sh     # submit {len(configs)} jobs")
    print(f"  5. python mlp/mlp_collect_results.py    # after all jobs finish")


if __name__ == "__main__":
    main()
