"""
htm_velocity/htm_velocity_prepare_windows.py
Pre-compute per-window velocity feature sequences for all (window_size, window_step)
combinations used by the HTM-Velocity hyperparameter search.

This is a ONE-TIME preparation step (re-run if velocity_cache.pkl or split.pkl change).

Each window is represented as an 8-tuple:
  (stats_21, key_idx, dwell_ms, flight_ms, dist_units, poly_mean, poly_med, poly_std)

Window pairs processed:
  window_size ∈ {10, 15},  window_step = 1

Usage (from project root):
  python htm_velocity/htm_velocity_prepare_windows.py           # all pairs
  python htm_velocity/htm_velocity_prepare_windows.py --task-id N  # single pair

Outputs:
  hv_windows_cache/ws{N}s{S}.pkl  for each (window_size, window_step) pair

Cache file format (dict):
  {
    'window_size': int,
    'window_step': int,
    'ref_dwells':  list[np.ndarray],
    'ref_flights': list[np.ndarray],
    'ref_dists':   list[np.ndarray],
    'sequences': {
        filepath: [(stats_21, key_idx, dwell, flight, dist, poly_mean, poly_med, poly_std), ...]
    }
  }
"""

import argparse
import os
import sys
import pickle
import multiprocessing as mp
from pathlib import Path

_project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _project_root not in sys.path:
    sys.path.insert(0, _project_root)

_htm_vel_dir = os.path.dirname(os.path.abspath(__file__))
if _htm_vel_dir not in sys.path:
    sys.path.insert(0, _htm_vel_dir)

_htm_combined_dir = os.path.join(_project_root, "htm_combined")
if _htm_combined_dir not in sys.path:
    sys.path.insert(0, _htm_combined_dir)

_htm_dist_dir = os.path.join(_project_root, "htm_distance")
if _htm_dist_dir not in sys.path:
    sys.path.insert(0, _htm_dist_dir)

os.chdir(_project_root)

from tqdm import tqdm
from common.keystroke_features import RANDOM_SEED
from htm_combined_common import create_reference_pool
from htm_velocity_common import get_file_velocity_seq

# ── Paths ─────────────────────────────────────────────────────────────────────
SPLIT_FILE   = "split.pkl"
CACHE_FILE   = "stats_cache.pkl"
DIST_CACHE   = "dist_cache.pkl"        # fallback, same format
VEL_CACHE    = "velocity_cache.pkl"
WINDOWS_DIR  = "hv_windows_cache"

# All (window_size, window_step) pairs in the velocity search space
WINDOW_PAIRS = [
    (ws, st)
    for ws in [10, 15]
    for st in [1]
]


# ── Multiprocessing worker (module-level so it is picklable) ──────────────────
_w_cache        = None
_w_vel_cache    = None
_w_ref_dwells   = None
_w_ref_flights  = None
_w_ref_dists    = None
_w_window_size  = None
_w_window_step  = None


def _init_worker(cache, vel_cache, ref_dwells, ref_flights, ref_dists,
                 window_size, window_step):
    global _w_cache, _w_vel_cache, _w_ref_dwells, _w_ref_flights, _w_ref_dists
    global _w_window_size, _w_window_step
    _w_cache       = cache
    _w_vel_cache   = vel_cache
    _w_ref_dwells  = ref_dwells
    _w_ref_flights = ref_flights
    _w_ref_dists   = ref_dists
    _w_window_size = window_size
    _w_window_step = window_step


def _process_file(fp):
    """Worker: compute velocity-window sequence for one file."""
    events     = _w_cache.get(fp)
    vel_events = _w_vel_cache.get(fp)
    if not events or not vel_events:
        return fp, None, True   # (path, seq, missing_from_cache)
    seq = get_file_velocity_seq(events, vel_events,
                                _w_window_size, _w_window_step,
                                _w_ref_dwells, _w_ref_flights, _w_ref_dists)
    return fp, seq if seq else None, False


def write_slurm_script(out_path: str = "slurm/hv_prepare_windows.sh"):
    script = """\
#!/bin/bash
# ============================================================
# SLURM job: HTM-Velocity windows cache preparation
# Generated by htm_velocity/htm_velocity_prepare_windows.py
#
# Run ONCE before submitting the hyperparameter search array.
# Safe to re-run -- existing cache files are skipped.
#
# Submit with:
#   sbatch slurm/hv_prepare_windows.sh
# ============================================================
#SBATCH --job-name=hv_prep_win
#SBATCH --output=logs/hv_prepare_windows_%A_%a.out
#SBATCH --error=logs/hv_prepare_windows_%A_%a.err
#SBATCH --array=0-1
#SBATCH --cpus-per-task=32
#SBATCH --mem=64G
#SBATCH --time=04:00:00
##SBATCH --partition=<partition>
##SBATCH --account=<account>

# ---- Environment ------------------------------------------------
source $(conda info --base)/etc/profile.d/conda.sh
conda activate htm_keyboard_1

# ---- Run --------------------------------------------------------
echo "========================================"
echo "Job   : $SLURM_JOB_ID"
echo "Task  : $SLURM_ARRAY_TASK_ID"
echo "Node  : $(hostname)"
echo "Start : $(date)"
echo "========================================"

python -u htm_velocity/htm_velocity_prepare_windows.py --task-id $SLURM_ARRAY_TASK_ID

echo "========================================"
echo "End   : $(date)"
echo "========================================"
"""
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, 'w', newline='\n') as fh:
        fh.write(script)
    print(f"SLURM script  -> {out_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Pre-compute per-window velocity feature sequences for HTM-Velocity")
    parser.add_argument("--task-id", type=int, default=None,
                        help="SLURM array task ID (0-1) to process a single window pair")
    args = parser.parse_args()

    os.makedirs(WINDOWS_DIR, exist_ok=True)

    # ── Load split ────────────────────────────────────────────────────────────
    if not os.path.exists(SPLIT_FILE):
        print(f"ERROR: {SPLIT_FILE} not found.  Run htm/htm_prepare_data.py first.")
        sys.exit(1)

    # ── Load stats cache ──────────────────────────────────────────────────────
    cache_path = CACHE_FILE if os.path.exists(CACHE_FILE) else DIST_CACHE
    if not os.path.exists(cache_path):
        print(f"ERROR: neither {CACHE_FILE} nor {DIST_CACHE} found.")
        sys.exit(1)
    if cache_path == DIST_CACHE:
        print(f"  Note: {CACHE_FILE} not found; using {DIST_CACHE} (same format).")

    # ── Load velocity cache ───────────────────────────────────────────────────
    if not os.path.exists(VEL_CACHE):
        print(f"ERROR: {VEL_CACHE} not found.")
        print("  Run: python htm_velocity/htm_velocity_prepare_data.py")
        sys.exit(1)

    print(f"Loading split from {SPLIT_FILE}...")
    with open(SPLIT_FILE, 'rb') as fh:
        split = pickle.load(fh)

    print(f"Loading keystroke cache from {cache_path}...")
    with open(cache_path, 'rb') as fh:
        cache = pickle.load(fh)

    print(f"Loading velocity cache from {VEL_CACHE}...")
    with open(VEL_CACHE, 'rb') as fh:
        vel_cache = pickle.load(fh)

    train_human = split['train_human']
    all_files   = (
        split['train_human'] + split['val_human'] + split['test_human'] +
        split['val_bots']   + split['test_bots']
    )
    # Deduplicate, preserving order
    seen:         set  = set()
    unique_files: list = []
    for fp in all_files:
        if fp not in seen:
            seen.add(fp)
            unique_files.append(fp)

    print(f"  {len(unique_files)} total files  "
          f"({len(split['train_human'])} train-h / "
          f"{len(split['val_human'])} val-h / "
          f"{len(split['test_human'])} test-h / "
          f"{len(split['val_bots'])} val-b / "
          f"{len(split['test_bots'])} test-b)")

    # Report velocity cache coverage
    in_vel = sum(1 for fp in unique_files if fp in vel_cache)
    print(f"  {in_vel}/{len(unique_files)} files in velocity_cache")

    # ── Determine which pairs to process ─────────────────────────────────────
    if args.task_id is not None:
        if 0 <= args.task_id < len(WINDOW_PAIRS):
            pairs_to_process = [WINDOW_PAIRS[args.task_id]]
            print(f"Processing single pair index {args.task_id}: {pairs_to_process[0]}")
        else:
            print(f"ERROR: --task-id {args.task_id} is out of range [0, {len(WINDOW_PAIRS)-1}]")
            sys.exit(1)
    else:
        pairs_to_process = WINDOW_PAIRS
        print(f"Processing all {len(pairs_to_process)} pairs sequentially")

    # ── Build cache for each (window_size, window_step) pair ─────────────────
    for window_size, window_step in pairs_to_process:
        out_path = os.path.join(WINDOWS_DIR, f"ws{window_size}s{window_step}.pkl")

        if os.path.exists(out_path):
            print(f"\n[ws={window_size} step={window_step}]  "
                  f"Already exists: {out_path}  (skipping)")
            continue

        print(f"\n{'='*60}")
        print(f"[ws={window_size} step={window_step}]  Building cache...")

        # Build reference pool from training human files (uses stats_cache format)
        ref_dwells, ref_flights, ref_dists = create_reference_pool(
            train_human, cache,
            window_size=window_size,
            seed=RANDOM_SEED)

        if not ref_dwells:
            print(f"  WARNING: Could not build reference pool "
                  f"(window_size={window_size} may exceed training files). Skipping.")
            continue

        sequences: dict = {}
        skipped = 0
        n_workers = int(os.environ.get("SLURM_CPUS_PER_TASK", mp.cpu_count()))
        print(f"  Using {n_workers} worker processes.")

        with mp.Pool(
            processes=n_workers,
            initializer=_init_worker,
            initargs=(cache, vel_cache, ref_dwells, ref_flights, ref_dists,
                      window_size, window_step),
        ) as pool:
            for fp, seq, missing in tqdm(
                pool.imap_unordered(_process_file, unique_files),
                total=len(unique_files),
                desc=f"  ws={window_size}s={window_step}",
            ):
                if missing:
                    skipped += 1
                elif seq is not None:
                    sequences[fp] = seq

        total_windows = sum(len(s) for s in sequences.values())
        print(f"  Sequences: {len(sequences)}/{len(unique_files)} files "
              f"({skipped} missing from cache)")
        print(f"  Total windows: {total_windows:,}")

        payload = {
            'window_size':  window_size,
            'window_step':  window_step,
            'ref_dwells':   ref_dwells,
            'ref_flights':  ref_flights,
            'ref_dists':    ref_dists,
            'sequences':    sequences,
        }
        with open(out_path, 'wb') as fh:
            pickle.dump(payload, fh, protocol=pickle.HIGHEST_PROTOCOL)
        print(f"  Saved -> {out_path}")

    print(f"\nDone.  All window caches written to {WINDOWS_DIR}/")

    write_slurm_script("slurm/hv_prepare_windows.sh")
    print("\nNext steps:")
    print("  python htm_velocity/htm_velocity_generate_configs.py --n-configs 128")
    print("  sbatch slurm/hv_submit_array.sh")


if __name__ == "__main__":
    main()
